var searchData=
[
  ['f32cpu_5fdm_0',['f32CPU_DM',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a7a852282f885457b351c692c3fe63cdda2b00bf32c73dc412ad8b09ad140fd7e5',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32cpu_5fdv_1',['f32CPU_DV',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a7a852282f885457b351c692c3fe63cddaac609bda818000e9826373695e236b46',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32cpu_5fsm_2',['f32CPU_SM',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a7a852282f885457b351c692c3fe63cdda4426ffa35cfceaed79e90a212845459c',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32cpu_5fsv_3',['f32CPU_SV',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a7a852282f885457b351c692c3fe63cdda0df31b8a801a067134fe0b88f1381db0',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32gpu_5fdm_4',['f32GPU_DM',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a1e0a6ba0fd2306c053d8e9d99c436c8ea63c087dd97858b3c0149f5fb7739dc2e',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32gpu_5fdv_5',['f32GPU_DV',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a1e0a6ba0fd2306c053d8e9d99c436c8ea8178a88d6cbc42b3113b27b37dfee1a2',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['f32gpu_5fsm_6',['f32GPU_SM',['../class_vector_search_interface_1_1_vector_search_a_p_i.html#a1e0a6ba0fd2306c053d8e9d99c436c8ead6104cdf9109c1c0975ce4536a0465f4',1,'VectorSearchInterface::VectorSearchAPI']]],
  ['findtopcandidates_7',['findtopcandidates',['../_vector_search_2dllmain_8cpp.html#a4b094ba26aecb4f6532d72327f0838c3',1,'findTopCandidates(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#a4b094ba26aecb4f6532d72327f0838c3',1,'findTopCandidates(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidates2_8',['findtopcandidates2',['../_vector_search_2dllmain_8cpp.html#a1590663fb100ad6d867d521fcc9fc15d',1,'findTopCandidates2(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#a1590663fb100ad6d867d521fcc9fc15d',1,'findTopCandidates2(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidates2int_9',['findtopcandidates2int',['../_vector_search_2dllmain_8cpp.html#af5ae3bfd3da723a956a4e2fb7e83c5d9',1,'findTopCandidates2Int(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#af5ae3bfd3da723a956a4e2fb7e83c5d9',1,'findTopCandidates2Int(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatesbatched_10',['findtopcandidatesbatched',['../_vector_search_2dllmain_8cpp.html#ac4bf0fc076052c4ecfceeb3d7218aaed',1,'findTopCandidatesBatched(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#ac4bf0fc076052c4ecfceeb3d7218aaed',1,'findTopCandidatesBatched(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatesbatched2_11',['findtopcandidatesbatched2',['../_vector_search_2dllmain_8cpp.html#a7907d6ef2acb528619b1e6c44d776ded',1,'findTopCandidatesBatched2(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#a7907d6ef2acb528619b1e6c44d776ded',1,'findTopCandidatesBatched2(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatesbatched2int_12',['findtopcandidatesbatched2int',['../_vector_search_2dllmain_8cpp.html#ab4dee50ac286d8928bc943317d35b426',1,'findTopCandidatesBatched2Int(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#ab4dee50ac286d8928bc943317d35b426',1,'findTopCandidatesBatched2Int(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatesbatchedint_13',['findtopcandidatesbatchedint',['../_vector_search_2dllmain_8cpp.html#a0e508362b43b14dc8b6cc5db21cf0d79',1,'findTopCandidatesBatchedInt(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#a0e508362b43b14dc8b6cc5db21cf0d79',1,'findTopCandidatesBatchedInt(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatescuda_14',['findtopcandidatescuda',['../find_top_candidates_cuda_int_8cpp.html#a5f8de50070510cb005cac6dffdefc579',1,'findTopCandidatesCuda(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int verbose):&#160;findTopCandidatesCudaInt.cpp'],['../_vector_search_c_u_d_a_2dllmain_8cpp.html#a54e13f53fef6807ee251f6d85433d33e',1,'findTopCandidatesCuda(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int verbose):&#160;dllmain.cpp'],['../_vector_search_c_u_d_a_2dllmain_unix_8cpp.html#a5f8de50070510cb005cac6dffdefc579',1,'findTopCandidatesCuda(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatescudabatched_15',['findtopcandidatescudabatched',['../find_top_candidates_cuda_int_8cpp.html#a0edefdf27ac3d394f1c8a070ffa5321f',1,'findTopCandidatesCudaBatched(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;findTopCandidatesCudaInt.cpp'],['../_vector_search_c_u_d_a_2dllmain_8cpp.html#a068531aefbe5c14ddb0d6ade29105d2f',1,'findTopCandidatesCudaBatched(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;dllmain.cpp'],['../_vector_search_c_u_d_a_2dllmain_unix_8cpp.html#a0edefdf27ac3d394f1c8a070ffa5321f',1,'findTopCandidatesCudaBatched(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatescudabatched2_16',['findtopcandidatescudabatched2',['../find_top_candidates_cuda_int_8cpp.html#aabc3d6b9cd29ba5f6934abffda9ddf55',1,'findTopCandidatesCudaBatched2(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;findTopCandidatesCudaInt.cpp'],['../_vector_search_c_u_d_a_2dllmain_8cpp.html#a50f076e2eb37074164cb188062e30691',1,'findTopCandidatesCudaBatched2(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;dllmain.cpp'],['../_vector_search_c_u_d_a_2dllmain_unix_8cpp.html#aabc3d6b9cd29ba5f6934abffda9ddf55',1,'findTopCandidatesCudaBatched2(int *csrRowoffsets, int *csrColIdx, int *spectraValues, int *spectraIdx, int csrRowoffsetsLength, int csrNNZ, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int batchSize, int verbose):&#160;dllmainUnix.cpp']]],
  ['findtopcandidatescudaint_17',['findTopCandidatesCudaInt',['../find_top_candidates_cuda_int_8cpp.html#a843bb6496ef7022dec76a700044300e9',1,'findTopCandidatesCudaInt.cpp']]],
  ['findtopcandidatescudaint_2ecpp_18',['findTopCandidatesCudaInt.cpp',['../find_top_candidates_cuda_int_8cpp.html',1,'']]],
  ['findtopcandidatesint_19',['findtopcandidatesint',['../_vector_search_2dllmain_8cpp.html#a6b599b363c1e78028597a3a769ea5da8',1,'findTopCandidatesInt(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmain.cpp'],['../_vector_search_2dllmain_unix_8cpp.html#a6b599b363c1e78028597a3a769ea5da8',1,'findTopCandidatesInt(int *candidatesValues, int *candidatesIdx, int *spectraValues, int *spectraIdx, int cVLength, int cILength, int sVLength, int sILength, int n, float tolerance, bool normalize, bool gaussianTol, int cores, int verbose):&#160;dllmainUnix.cpp']]],
  ['framework_2eh_20',['framework.h',['../_vector_search_2framework_8h.html',1,'(Global Namespace)'],['../_vector_search_c_u_d_a_2framework_8h.html',1,'(Global Namespace)']]]
];
