name: Build for macOS

on:
  workflow_dispatch:

jobs:
  Build-for-macOS:
    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install XCode
        run: |
          xcode-select --install
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install gcc
        run: |
          brew install gcc
      - name: Copy and unzip eigen
        run: |
          cp eigen-3.4.0.zip VectorSearch
          cd VectorSearch
          unzip eigen-3.4.0.zip
      - name: Build VectorSearch.dll dynamic library
        run: |
          cd VectorSearch
          g++ -shared -I eigen-3.4.0 -fPIC -fopenmp -O3 -o VectorSearch.dll dllmainUnix.cpp
          cp VectorSearch.dll ..
      - name: Build DataLoader
        steps:
          - uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '6'
          - run: |
              cd DataLoader
              dotnet publish DataLoader.csproj --runtime osx-arm64 --self-contained --configuration Release
      - name: Copy VectorSearch.dll to Release
        run: |
          cp VectorSearch.dll DataLoader/bin/Release/net6.0/osx-arm64
      - name: Zip Release
        run: |
          cd DataLoader/bin/
          zip -r Release.zip Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-arm64-cpu-only
          path: DataLoader/bin/Release.zip
