name: Test for generic Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-for-Linux:
    runs-on: ubuntu-22.04
    container: debian:bookworm
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y g++
      - name: Test
        run: |
          cd DataLoaderExecutable/linux_x64/uncompressed
          ./DataLoader EigenSIntB 10000
