name: Build for macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-for-macOS:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Test
        run: |
          cd DataLoaderExecutable/macos_arm/uncompressed
          ./DataLoader EigenSIntB 10000
