name: Test for generic Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-for-Linux:
    runs-on: ubuntu-22.04
    container: debian:bookworm
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl \
          g++ \
          libc6 \
          libgcc-s1 \
          libgssapi-krb5-2 \
          libicu72 \
          libssl1.1 \
          libstdc++6 \
          zlib1g
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Test
        run: |
          cd DataLoaderExecutable/linux_x64/uncompressed
          chmod +x DataLoader
          ./DataLoader EigenSIntB 10000
